# Generated by Django 5.2.4 on 2026-07-21 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Étudiant'), ('SUPERVISOR', 'Encadreur'), ('ADMIN', 'Administrateur')], default='STUDENT', max_length=20, verbose_name='Rôle')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='Niveau académique')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
