# Generated by Django 5.2.4 on 2026-07-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('LICENCE_1', 'Licence 1'), ('LICENCE_2', 'Licence 2'), ('LICENCE_3', 'Licence 3'), ('MASTER_1', 'Master 1'), ('MASTER_2', 'Master 2')], default='LICENCE_1', max_length=20, verbose_name='Niveau académique'),
        ),
    ]
