# Generated by Django 5.2.4 on 2026-07-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_filiere_niveau_remove_profile_level_profile_filiere_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['code'], 'verbose_name': "Niveau d'étude", 'verbose_name_plural': "Niveaux d'étude"},
        ),
        migrations.RemoveField(
            model_name='niveau',
            name='ordre',
        ),
    ]
